apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncoptionsdemo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd-app4mcli-ns  
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/With_Schema_Error
    repoURL: 'https://github.com/sagar2github/Udemy-ArgoCD-Muthukumar.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
