apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selfhealtestapp
  namespace: argocdapp2
spec:
  destination:
    namespace: argocdappdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Nginx_Deployment
    repoURL: 'https://github.com/sagar2github/Udemy-ArgoCD-Muthukumar.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
