apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: argocd-prune-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: argocd-prune-ns
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: example-configmap
#   namespace: argocd-prune-ns
# data:
#   key1: value1
#   key2: value2
